name: apnifasaladmin
description: A new Flutter project.

# The following defines the environment your project is compatible with
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.4
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # Other dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0

# Add the following if it’s missing
flutter:
  uses-material-design: true

  # Correct asset structure
  assets:
    - assets/apnifasal_black_logo.png
    - assets/apnifasal_white_logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/apnifasal_white_logo.png"


